[package]
name = "softeelab"
version = "0.1.0"
authors = ["Marco Cosentino <cosentino.ma@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
simple_logger = "1.0.1"
yaml-rust = "0.4.2"
clap = "2.32.0"
